name: ${name}
description: ${description}
version: ${version}
author: Khron. Para más información ver repositorio de GitHub
main: io.github.alextmjugador.khron.tiemporeal.PluginTiempoReal
depend: [GestorBarraAccion]
api-version: 1.13
commands:
    trconfig:
        description: Cambia la configuración.
        aliases: trcfg
        permission: tiemporeal.trconfig
        permission-message: ""
        usage: "Sintaxis: /<command> [parámetro] [valor]"
    trrecargarconfig:
        description: Recarga la configuración.
        aliases: [ trrcfg, trrecargarcfg, trreccfg, trrecconfig ]
        permission: tiemporeal.trrecargarconfig
        permission-message: ""
        usage: "Sintaxis: /<command>"
permissions:
    tiemporeal.*:
        description: Permite acceso total a los comandos del plugin.
        default: op
        children:
            tiemporeal.trconfig.*: true
            tiemporeal.trrecargarconfig: true
    tiemporeal.trconfig.*:
        description: Permite cambiar todos los parámetros de configuración del plugin.
        children:
            tiemporeal.trconfig.mundosSinc: true
            tiemporeal.trconfig.textoHora: true
    tiemporeal.trconfig.mundosSinc:
        description: Permite cambiar en qué mundos ${name} sincroniza la hora con la del servidor.
    tiemporeal.trconfig.textoHora:
        description: Permite cambiar el texto que ${name} mostrará a los jugadores cuando empuñen un reloj.
    tiemporeal.trrecargarconfig:
        description: Permite recargar la configuración de ${name} desde disco.