name: ${name}
description: ${description}
version: ${version}
author: Khron. Para más información ver repositorio de GitHub
main: io.github.alextmjugador.khron.gestorbarraaccion.PluginGestorBarraAccion
depend: [ActionBarAPI]
api-version: 1.15