name: Maven CI

on: [push, pull_request]

jobs:
  build:

    runs-on: [linux, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Configuración JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Compilar con Maven
      run: mvn -B package --file pom.xml
